name: Release
on:
  push:
    tags:
      - "v*"
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build
        run: pnpm run build
      - name: Package plugin
        run: |
          zip -r notion-api-importer.zip manifest.json dist
      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: notion-api-importer.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
